In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Travel2.csv")

In [3]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [89]:
df["ProdTaken"].value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [4]:
df["TypeofContact"].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [5]:
df["Occupation"].value_counts()

Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64

In [6]:
df["Gender"].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [7]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [9]:
df["Designation"].value_counts()

Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [12]:
df["Gender"] = df["Gender"].replace("Fe Male","Female")

In [13]:
df["MaritalStatus"] = df["MaritalStatus"].replace("Single","Unmarried")

In [15]:
df["Gender"].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [16]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [17]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [18]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [19]:
df.Age.fillna(df.Age.median(),inplace = True)
df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)
df.DurationOfPitch.fillna(df.DurationOfPitch.median(),inplace = True)
df.NumberOfFollowups.fillna(df.NumberOfFollowups.median(),inplace = True)
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.median(),inplace = True)
df.NumberOfTrips.fillna(df.NumberOfTrips.median(),inplace = True)
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.median(),inplace = True)
df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace = True)

/var/folders/q_/2jj5k2850fq_pnfq8g_pl8l80000gn/T/ipykernel_14042/4176512687.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Age.fillna(df.Age.median(),inplace = True)
/var/folders/q_/2jj5k2850fq_pnfq8g_pl8l80000gn/T/ipykernel_14042/4176512687.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)
/var/folders/q_/2jj5k2850fq_pnfq8g_pl8l80000gn/T/ipykernel_14042/4176512687.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.DurationOfPitch.fillna(df.DurationOfPitch.median(),inplace = True)
/var/folders/q_/2jj5k2850fq_pnfq8g_pl8l80000gn/T/ipykernel_14042/4176512687.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.NumberOfFollowups.fillna(df.NumberOfFollowups.median(),inplace = True)
/var/folders/q_/2jj5k2850fq_pnfq8g_pl8l80000gn/T/ipykernel_14042/4176512687.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.median(),inplace = True)
/var/folders/q_/2jj5k2850fq_pnfq8g_pl8l80000gn/T/ipykernel_14042/4176512687.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.NumberOfTrips.fillna(df.NumberOfTrips.median(),inplace = True)
/var/folders/q_/2jj5k2850fq_pnfq8g_pl8l80000gn/T/ipykernel_14042/4176512687.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.median(),inplace = True)
/var/folders/q_/2jj5k2850fq_pnfq8g_pl8l80000gn/T/ipykernel_14042/4176512687.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace = True)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4888 non-null   float64
 3   TypeofContact             4888 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4888 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4888 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4888 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4888 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4888 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4888 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [22]:
df["TotalVisiting"] = df["NumberOfPersonVisiting"]+df["NumberOfChildrenVisiting"]
df.drop(columns=["NumberOfPersonVisiting","NumberOfChildrenVisiting"],axis=1,inplace=True)

In [23]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [24]:
df.isnull().sum()

CustomerID                0
ProdTaken                 0
Age                       0
TypeofContact             0
CityTier                  0
DurationOfPitch           0
Occupation                0
Gender                    0
NumberOfFollowups         0
ProductPitched            0
PreferredPropertyStar     0
MaritalStatus             0
NumberOfTrips             0
Passport                  0
PitchSatisfactionScore    0
OwnCar                    0
Designation               0
MonthlyIncome             0
TotalVisiting             0
dtype: int64

In [25]:
#traintestsplit
from sklearn.model_selection import train_test_split
X = df.drop("ProdTaken",axis=1)
y = df["ProdTaken"]

In [26]:
X

,CustomerID,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,200000,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,200001,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,200002,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,200003,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,200004,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,49.0,Self Enquiry,3,9.0,Small Business,Male,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,Manager,26576.0,4.0
4884,204884,28.0,Company Invited,1,31.0,Salaried,Male,5.0,Basic,3.0,Unmarried,3.0,1,3,1,Executive,21212.0,6.0
4885,204885,52.0,Self Enquiry,3,17.0,Salaried,Female,4.0,Standard,4.0,Married,7.0,0,1,1,Senior Manager,31820.0,7.0
4886,204886,19.0,Self Enquiry,3,16.0,Small Business,Male,4.0,Basic,3.0,Unmarried,3.0,0,5,0,Executive,20289.0,5.0
4887,204887,36.0,Self Enquiry,1,14.0,Salaried,Male,4.0,Basic,4.0,Unmarried,3.0,1,3,1,Executive,24041.0,6.0

In [27]:
y

0       1
1       0
2       1
3       0
4       0
       ..
4883    1
4884    1
4885    1
4886    1
4887    1
Name: ProdTaken, Length: 4888, dtype: int64

In [28]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [39]:
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import ColumnTransformer
num_transform = StandardScaler()
cat_transform = OneHotEncoder(drop="first")
preprocessor = ColumnTransformer(
    [ ("OneHotEncoding",cat_transform,cat_features),
     ("StandarScaler",num_transform,num_features)
    ]
)

In [40]:
print(preprocessor)

ColumnTransformer(transformers=[('OneHotEncoding', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')),
                                ('StandarScaler', StandardScaler(),
                                 Index(['CustomerID', 'Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object'))])

In [41]:
X_train = preprocessor.fit_transform(X_train)

In [42]:
X_train

array([[ 1.        ,  0.        ,  1.        , ...,  0.78143477,
         0.4603181 , -0.06786916],
       [ 1.        ,  1.        ,  0.        , ..., -1.27969734,
        -1.00566841, -0.777901  ],
       [ 1.        ,  0.        ,  1.        , ...,  0.78143477,
        -1.2097217 , -0.06786916],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.78143477,
        -0.35739958,  0.64216267],
       [ 1.        ,  0.        ,  0.        , ...,  0.78143477,
        -0.25076528,  0.64216267],
       [ 0.        ,  0.        ,  1.        , ..., -1.27969734,
        -1.07168012, -1.48793284]])

In [43]:
X_test = preprocessor.transform(X_test)

In [44]:
X_test

array([[ 0.        ,  0.        ,  0.        , ..., -1.27969734,
        -0.73033753, -0.777901  ],
       [ 1.        ,  0.        ,  0.        , ..., -1.27969734,
        -0.66394968, -0.06786916],
       [ 1.        ,  0.        ,  0.        , ...,  0.78143477,
        -0.417017  , -0.777901  ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.78143477,
        -0.08075222, -0.06786916],
       [ 1.        ,  0.        ,  1.        , ...,  0.78143477,
         1.97576639, -0.06786916],
       [ 1.        ,  0.        ,  1.        , ..., -1.27969734,
         1.28837951, -1.48793284]])

In [45]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,-0.714031,-0.649789,0.280718,-0.727208,-1.217370,-0.632714,1.409081,0.781435,0.460318,-0.067869
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,-0.714031,-0.527737,-0.719632,1.768057,1.504605,-0.632714,1.409081,-1.279697,-1.005668,-0.777901
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.161582,1.281068,1.768057,-0.672975,1.580492,-0.046813,0.781435,-1.209722,-0.067869
3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.470853,-0.771841,0.280718,0.520424,-0.128580,1.580492,-0.046813,0.781435,-0.017750,0.642163
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.527737,1.281068,0.520424,2.593396,-0.632714,0.681134,-1.279697,-0.423411,-0.067869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3416,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.649789,1.281068,-0.727208,-0.672975,-0.632714,-1.502707,0.781435,-0.531926,0.642163
3417,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.470853,-0.893893,-0.719632,1.768057,-1.217370,-0.632714,1.409081,0.781435,1.512744,-0.067869
3418,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.470853,1.547143,0.280718,-0.727208,2.049001,-0.632714,-0.774760,0.781435,-0.357400,0.642163
3419,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.470853,1.791246,1.281068,-0.727208,-0.128580,-0.632714,-1.502707,0.781435,-0.250765,0.642163
3420,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.771841,0.280718,-0.727208,-1.217370,1.580492,-0.046813,-1.279697,-1.071680,-1.487933

In [49]:
!pip install xgboost
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier 
from xgboost import XGBClassifier 
from sklearn.metrics import accuracy_score,classification_report,precision_score,recall_score,f1_score,roc_auc_score

Requirement already satisfied: xgboost in /opt/anaconda3/lib/python3.13/site-packages (3.1.3)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (1.15.3)

In [56]:
models = {
    "RandomForest" : RandomForestClassifier(),
    "GradientBoost" :GradientBoostingClassifier(),
    "Adaboost" : AdaBoostClassifier(),
    "Xgboost" : XGBClassifier()
}

for i in range (len(list(models))) :
    model = list(models.values())[i]
    model.fit(X_train,y_train) 

#predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

#accuracy check training data
    classification_rep = classification_report(y_train,y_train_pred)
    acc_score = accuracy_score(y_train,y_train_pred)
    prec_score = precision_score(y_train,y_train_pred)
    rec_score = recall_score(y_train,y_train_pred)
    f1_Score  = f1_score(y_train,y_train_pred,average="weighted")
    roc_auc = roc_auc_score(y_train,y_train_pred)

#acc check test data 
# Test set performance
    model_test_accuracy = accuracy_score(y_test, y_test_pred) # Calculate Accuracy
    model_test_f1 = f1_score(y_test, y_test_pred, average='weighted') # Calculate F1-score
    model_test_precision = precision_score(y_test, y_test_pred) # Calculate Precision
    model_test_recall = recall_score(y_test, y_test_pred) # Calculate Recall
    model_test_rocauc_score = roc_auc_score(y_test, y_test_pred) #Calculate Roc

    print(list(models.keys())[i])
    print('Model performance for Training set')
    print("- Accuracy: {:.4f}".format(acc_score))
    print('- F1 score: {:.4f}'.format(f1_Score))
    
    print('- Precision: {:.4f}'.format(prec_score))
    print('- Recall: {:.4f}'.format(rec_score))
    print('- Roc Auc Score: {:.4f}'.format(roc_auc))
    
    
    print('----------------------------------')
    
    print('Model performance for Test set')
    print('- Accuracy: {:.4f}'.format(model_test_accuracy))
    print('- F1 score: {:.4f}'.format(model_test_f1))
    print('- Precision: {:.4f}'.format(model_test_precision))
    print('- Recall: {:.4f}'.format(model_test_recall))
    print('- Roc Auc Score: {:.4f}'.format(model_test_rocauc_score))

    print("-"*40)
    print("\n")

RandomForest
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9080
- F1 score: 0.8976
- Precision: 0.9427
- Recall: 0.5401
- Roc Auc Score: 0.7663
----------------------------------------


GradientBoost
Model performance for Training set
- Accuracy: 0.8942
- F1 score: 0.8819
- Precision: 0.8923
- Recall: 0.5000
- Roc Auc Score: 0.7430
----------------------------------
Model performance for Test set
- Accuracy: 0.8657
- F1 score: 0.8462
- Precision: 0.7895
- Recall: 0.3832
- Roc Auc Score: 0.6799
----------------------------------------


Adaboost
Model performance for Training set
- Accuracy: 0.8524
- F1 score: 0.8210
- Precision: 0.8249
- Recall: 0.2771
- Roc Auc Score: 0.6317
----------------------------------
Model performance for Test set
- Accuracy: 0.8432
- F1 score: 0.8115
- Precision: 0.7245
- Recall: 0.2591
- Roc Auc Score: 0.6182
----------------------------------------


Xgboost
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9162
- F1 score: 0.9101
- Precision: 0.8953
- Recall: 0.6241
- Roc Auc Score: 0.8037
----------------------------------------

In [68]:
#hyperparameter tuning 
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "sqrt", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}
xgboost_params = { "learning_rate" : [0.1,0.01],
                  "n_estimators" : [100,200,300],
                  "max_depth" : [2,8,12,20,30] ,
                  "colsample_bytree": [0.5,0.3,0.8,1,0.4]}

In [69]:
# Models list for Hyperparameter tuning
randomcv_models = [
                   ("RF", RandomForestClassifier(), rf_params),
    ("xgb", XGBClassifier(), xgboost_params) ]

In [70]:
randomcv_models

[('RF',
  RandomForestClassifier(),
  {'max_depth': [5, 8, 15, None, 10],
   'max_features': [5, 7, 'sqrt', 8],
   'min_samples_split': [2, 8, 15, 20],
   'n_estimators': [100, 200, 500, 1000]}),
 ('xgb',
  XGBClassifier(base_score=None, booster=None, callbacks=None,
                colsample_bylevel=None, colsample_bynode=None,
                colsample_bytree=None, device=None, early_stopping_rounds=None,
                enable_categorical=False, eval_metric=None, feature_types=None,
                feature_weights=None, gamma=None, grow_policy=None,
                importance_type=None, interaction_constraints=None,
                learning_rate=None, max_bin=None, max_cat_threshold=None,
                max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
                max_leaves=None, min_child_weight=None, missing=nan,
                monotone_constraints=None, multi_strategy=None, n_estimators=None,
                n_jobs=None, num_parallel_tree=None, ...),
  {'learning_rate': [0.1, 0.01],
   'n_estimators': [100, 200, 300],
   'max_depth': [2, 8, 12, 20, 30],
   'colsample_bytree': [0.5, 0.3, 0.8, 1, 0.4]})]

In [71]:
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                   param_distributions=params,
                                   n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
    random.fit(X_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=500; total time=   0.6s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=200; total time=   0.3s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=500; total time=   0.7s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=1000; total time=   1.8s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=200; total time=   0.5s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=500; total time=   0.8s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=1000; total time=   2.3s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=500; total time=   1.0s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=200; total time=   0.4s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=500; total time=   0.8s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=200; total time=   0.5s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=500; total time=   0.8s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=200; total time=   0.5s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=500; total time=   1.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=1000; total time=   1.7s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=500; total time=   0.8s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=500; total time=   0.7s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=20, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=30, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=8, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=20, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=8, n_estimator=100; total time=   0.0s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=8, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=12, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=12, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=20, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=20, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=12, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=30, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=12, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=12, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=12, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=12, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=30, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=2, n_estimator=300; total time=   0.0s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=20, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=2, n_estimator=200; total time=   0.0s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=2, n_estimator=100; total time=   0.0s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=8, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=30, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=8, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=2, n_estimator=300; total time=   0.0s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=2, n_estimator=300; total time=   0.0s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=12, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=30, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=20, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=20, n_estimator=100; total time=   0.1s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=200; total time=   0.5s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=500; total time=   1.2s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=200; total time=   0.4s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=200; total time=   0.4s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=500; total time=   1.0s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=200; total time=   0.5s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=200; total time=   0.4s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=500; total time=   0.9s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=500; total time=   1.1s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   1.2s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=200; total time=   0.5s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=500; total time=   0.8s
[CV] END max_depth=15, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=500; total time=   0.6s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=500; total time=   0.7s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=1000; total time=   1.8s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=500; total time=   0.8s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=500; total time=   1.0s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=200; total time=   0.5s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=1000; total time=   2.4s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=200; total time=   0.3s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=200; total time=   0.3s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   0.5s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=500; total time=   0.6s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   0.4s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=1000; total time=   2.7s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.2s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=500; total time=   1.0s
[CV] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=200; total time=   0.3s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.2s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=500; total time=   1.1s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=500; total time=   0.9s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=1000; total time=   1.9s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=20, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=30, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=20, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=20, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=12, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=12, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=30, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=30, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=20, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=2, n_estimator=100; total time=   0.0s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=8, n_estimator=200; total time=   0.0s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=30, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=20, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=30, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=30, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=30, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=20, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=20, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=20, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=12, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=2, n_estimator=200; total time=   0.0s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=2, n_estimator=200; total time=   0.0s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=2, n_estimator=300; total time=   0.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=8, n_estimator=100; total time=   0.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=30, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=30, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimator=300; total time=   0.0s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=8, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=2, n_estimator=200; total time=   0.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=2, n_estimator=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=200; total time=   0.5s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=100; total time=   0.2s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=100; total time=   0.2s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=1000; total time=   1.7s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=1000; total time=   1.7s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=500; total time=   0.9s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.2s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500; total time=   0.8s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.3s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=1000; total time=   1.6s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=1000; total time=   1.7s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=200; total time=   0.4s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=500; total time=   0.8s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=500; total time=   1.0s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=200; total time=   0.5s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=1000; total time=   2.4s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=200; total time=   0.5s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=200; total time=   0.3s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   0.5s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=500; total time=   0.8s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.2s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=200; total time=   0.5s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=500; total time=   0.8s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=1000; total time=   1.8s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=1000; total time=   2.1s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.2s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=500; total time=   1.1s
[CV] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=1000; total time=   1.6s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=1000; total time=   1.2s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=8, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=30, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=20, n_estimator=200; total time=   0.2s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=20, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=2, n_estimator=200; total time=   0.0s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=12, n_estimator=300; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimator=200; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimator=200; total time=   0.0s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=2, n_estimator=100; total time=   0.0s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=2, n_estimator=100; total time=   0.0s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=8, n_estimator=200; total time=   0.1s

In [74]:
models={
    
    "Random Forest":RandomForestClassifier(n_estimators=1000,min_samples_split=2,
                                          max_features=7,max_depth=None),
    "XBboost": XGBClassifier(learning_rate=0.1,n_estimators =200,max_depth = 12 ,colsample_bytree = 1)
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

#predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

#accuracy check training data
    classification_rep = classification_report(y_train,y_train_pred)
    acc_score = accuracy_score(y_train,y_train_pred)
    prec_score = precision_score(y_train,y_train_pred)
    rec_score = recall_score(y_train,y_train_pred)
    f1_Score  = f1_score(y_train,y_train_pred,average="weighted")
    roc_auc = roc_auc_score(y_train,y_train_pred)

#acc check test data 
# Test set performance
    model_test_accuracy = accuracy_score(y_test, y_test_pred) # Calculate Accuracy
    model_test_f1 = f1_score(y_test, y_test_pred, average='weighted') # Calculate F1-score
    model_test_precision = precision_score(y_test, y_test_pred) # Calculate Precision
    model_test_recall = recall_score(y_test, y_test_pred) # Calculate Recall
    model_test_rocauc_score = roc_auc_score(y_test, y_test_pred) #Calculate Roc

    print(list(models.keys())[i])
    print('Model performance for Training set')
    print("- Accuracy: {:.4f}".format(acc_score))
    print('- F1 score: {:.4f}'.format(f1_Score))
    
    print('- Precision: {:.4f}'.format(prec_score))
    print('- Recall: {:.4f}'.format(rec_score))
    print('- Roc Auc Score: {:.4f}'.format(roc_auc))
    
    
    print('----------------------------------')
    
    print('Model performance for Test set')
    print('- Accuracy: {:.4f}'.format(model_test_accuracy))
    print('- F1 score: {:.4f}'.format(model_test_f1))
    print('- Precision: {:.4f}'.format(model_test_precision))
    print('- Recall: {:.4f}'.format(model_test_recall))
    print('- Roc Auc Score: {:.4f}'.format(model_test_rocauc_score))

    print("-"*40)
    print("\n")

Random Forest
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9121
- F1 score: 0.9039
- Precision: 0.9191
- Recall: 0.5803
- Roc Auc Score: 0.7843
----------------------------------------


XBboost
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9277
- F1 score: 0.9226
- Precision: 0.9375
- Recall: 0.6569
- Roc Auc Score: 0.8234
----------------------------------------

In [82]:
test_row_2 = {
    'CustomerID':300001,
    'Age': 30.0, 
    'TypeofContact': 'Self Enquiry', 
    'CityTier': 1, 
    'DurationOfPitch': 30.0, 
    'Occupation': 'Salaried', 
    'Gender': 'Male', 
    'NumberOfPersonVisiting': 3, 
    'NumberOfFollowups': 3.0, 
    'ProductPitched': 'Basic', 
    'PreferredPropertyStar': 3.0, 
    'MaritalStatus': 'Married', 
    'NumberOfTrips': 2.0, 
    'Passport': 0, 
    'PitchSatisfactionScore': 2, 
    'OwnCar': 0, 
    'NumberOfChildrenVisiting': 1.0, 
    'Designation': 'Executive', 
    'MonthlyIncome': 17693.0,
    'Random_Feature': -1.24  # Use this if you included the random column
}
new = pd.DataFrame([test_row_2])
new["TotalVisiting"] = new['NumberOfPersonVisiting']+new['NumberOfChildrenVisiting']
new.drop(columns=["NumberOfPersonVisiting","NumberOfChildrenVisiting"],axis=1,inplace=True)

In [83]:
new

,CustomerID,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,Random_Feature,TotalVisiting
0,300001,30.0,Self Enquiry,1,30.0,Salaried,Male,3.0,Basic,3.0,Married,2.0,0,2,0,Executive,17693.0,-1.24,4.0

In [84]:
new_transformed = preprocessor.transform(new)

In [85]:
new_transformed

array([[ 1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         6.94811990e+01, -8.13368019e-01, -7.14031176e-01,
         1.79124637e+00, -7.19632236e-01, -7.27208353e-01,
        -6.72974785e-01, -6.32714364e-01, -7.74760295e-01,
        -1.27969734e+00, -1.10177093e+00, -6.78691642e-02]])

In [88]:
xgbboost = XGBClassifier(learning_rate=0.1,n_estimators =200,max_depth = 12 ,colsample_bytree = 1)
xgbboost.fit(X_train,y_train)

predict_new = xgbboost.predict(new_transformed)

if predict_new[0] == 1:
    print("Prediction: The customer IS likely to take the product.")
else:
    print("Prediction: The customer is NOT likely to take the product.")

Prediction: The customer IS likely to take the product.

In [91]:
print(predict_new)

[1]

In [1]:
!git --version

git version 2.50.1 (Apple Git-155)